name: flutterfirebase
description: Firebase Auth App

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  firebase_auth: "0.11.1+7"
  firebase_database: ^3.0.5
  connectivity: ^0.4.3+6
  rflutter_alert: ^1.0.3
  fluttertoast: ^3.1.0
  modal_progress_hud: ^0.1.3
  flutter_facebook_login: ^2.0.1
  google_sign_in: ^4.0.4
  firebase_core: 0.4.0+8
  cloud_firestore: ^0.12.9
  firebase_messaging: ^5.1.2
  flutter_local_notifications: ^0.8.0
  cached_network_image: ^1.1.1
  shared_preferences: 0.5.3+4
  firebase_storage: 3.0.3
  intl: ^0.15.7
  image_picker: 0.6.1
  

dev_dependencies:
  flutter_launcher_icons: ^0.7.2+1
  font_awesome_flutter: ^8.5.0
flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/img/launch_icon.png"

  flutter_test:
    sdk: flutter
  


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
      - assets/img/google1.png
      - assets/img/facebook.png
      - assets/music/beep.mp3
      - assets/img/man.png
      - assets/img/cover.jpg
      - images/img_not_available.jpeg
      - images/mimi1.gif
      - images/mimi2.gif
      - images/mimi3.gif
      - images/mimi4.gif
      - images/mimi5.gif
      - images/mimi6.gif
      - images/mimi7.gif
      - images/mimi8.gif
      - images/mimi9.gif

  fonts:
    - family: DigitalTime
      fonts:
        - asset: assets/fonts/digital_7.ttf
    - family: WorkSansSemiBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-SemiBold.ttf

    - family: WorkSansBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Bold.ttf

    - family: WorkSansMedium
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Medium.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
